---
kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: build_agent_host
  user:
    from_secret: build_agent_user
  ssh_key:
    from_secret: build_agent_key

steps:
- name: init dependencies
  commands:
    - git submodule update --init --remote
